#cloud-config
autoinstall:
    version: 1
    identity:
        realname: 'Matheus Augusto'
        hostname: ubuntu-desktop
        username: Matheus
        password: '$y$j9T$uhkxlm8nUQaNu.6rl4k2d.$DIldpYy96OHg8lFjfXfc671BZcGWkPOmaDONGAhGSg3'
    locale: pt_BR.utf8
    keyboard:
        layout: br
    timezone: "America/Sao_Paulo"   
    packages:
        - net-tools
        - git
        - wget
    snaps:
        - name: code
          channel: stable
          classic: true
        - name: clouds
          channel: stable

    codecs:
        install: true
    drivers:
        install: true
    updates: all
    shutdown: reboot
